name: Docker buildx CI

env:
  DOCKERHUB_REPO: ghcr.io/araven/focalboard-docker
  FOCALBOARD_MAJOR: 0
  FOCALBOARD_MINOR: 12
  FOCALBOARD_INCREMENT: 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Github Container Registry login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64/v8
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          build-args: FOCALBOARD_REF=v${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}.${{ env.FOCALBOARD_INCREMENT }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}.${{ env.FOCALBOARD_INCREMENT }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}
            ${{ env.DOCKERHUB_REPO }}:latest
